parameters:
#    medical_health.example.class: Medical\HealthBundle\Example

services:
#    medical_health.example:
#        class: %medical_health.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
