<?php

namespace Medical\HealthBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Doctor_DiseaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Doctor_DiseaseRepository extends EntityRepository
{
}
