<?php

namespace Medical\HealthBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * History_DoctorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class History_DoctorRepository extends EntityRepository
{
}
