<?php

namespace Medical\HealthBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrescriptionRepository extends EntityRepository
{
}
